import OrcsAndGoblins from "../OrcsAndGoblins";
import MagicResistance from "../../SpecialRules/MagicResistance";
import OrcAndGoblinMagic from "../../SpecialRules/OrcAndGoblinMagic";

const GoblinMagic = (spellsPerTurn, modifier = 0) => OrcAndGoblinMagic(
    spellsPerTurn,
    `
        At the start of each monsters' phase, a Goblin Shaman may cast ${spellsPerTurn} of the following spells.
        Roll 2D6 on the following table to determine which.
    `,
    modifier - 2
);

export function GoblinShaman() {
    return {
        singularName: "Goblin Shaman",
        pluralName: "Goblin Shamans",
        description: "Although not as powerful as Orc Shamans, Goblin Shamans also practise a crude form of Orcish " +
            "magic, drawing on the power of the Waaagh! generated by other Goblins around them.",
        race: OrcsAndGoblins,
        wounds: 3,
        move: 4,
        weaponSkill: 2,
        ballisticSkill: 5,
        strength: 3,
        toughness: 4,
        initiative: 3,
        attacks: 1,
        gold: 280,
        armour: 0,
        damage: "1D6",
        specialRules: [
            GoblinMagic(1),
            MagicResistance(5, "Ring"),
        ],
    };
}

export default [
    {name: "Goblin Shamans", constructor: GoblinShaman},
];
